### ISSUE TITLE
[intl] Support for country code on i18n

### ISSUE THREAD

**Issue by chen-yumin** [timfreiheit/r_flutter#17]
### Description

Currently, `r_flutter` does not support locales with country code or script code. For example, if we want to distinguish between `zh_CN.arb` (for China) and `zh_HK.arb` (for Hong Kong), the generation would fail with an exception.

```dart
// Full Chinese support for CN, TW, and HK
supportedLocales: [
  const Locale.fromSubtags(languageCode: 'zh'), // generic Chinese 'zh'
  const Locale.fromSubtags(languageCode: 'zh', countryCode: 'CN'), // 'zh_CN'
  const Locale.fromSubtags(languageCode: 'zh', countryCode: 'TW'), // 'zh_TW'
  const Locale.fromSubtags(languageCode: 'zh', countryCode: 'HK'), // 'zh_HK'
],
```

### Proposal

Support `{language_code}_{country_code}.arb` file names instead of just  `{language_code}.arb`.

For example: 
- `zh_CN.arb` for China, `zh_HK.arb` for Hong Kong, and `zh_TW.arb` for Taiwan.
- `en_US.arb` for US English, and `en_UK.arb` for UK English.

**Comment by timfreiheit** [comment]
this should already be supported. It seams like there currently is a bug that the code generation fails when there is no support for the base language without the country addition.
When you include `zh_HK.arb` as well as `zh.arb` for example this should work fine.

**Comment by chen-yumin** [comment]
Yep. After creating the `zh.arb` it works like a charm. Thanks for the help!

Let me know if you'd like a PR to update the README documentation on this because it currently only states: 

> Other locales will be searched at `lib/i18n/<locale>.arb`

**Comment by timfreiheit** [comment]
version 0.5.1 fixes the bug. Your project does not need support for the base language anymore.

**Comment by chen-yumin** [comment]
Thanks for the update! That's a good enhancement since I don't want to copy the base language to be an exact duplicate as one of its specific ones.

Another feature request I have on the locale is the ability to specify the script code there as well. For example: `zh_Hans.arb` and `zh_Hant.arb` for generic simplified Chinese 'zh_Hans' and traditional script 'zh_Hant'. The locale would transpile into the following dart code:

```
// Full Chinese support for zh_Hans and zh_Hant
supportedLocales: [
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'), // generic simplified Chinese 'zh_Hans'
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'), // generic traditional Chinese 'zh_Hant'
```

This would be useful, for example, for the Chinese language, because the localization would correspond closely to the system's language instead of region. For example, on iOS you could select system language to be Traditional Chinese despite having the region set to China. And the localization should match this.

----

According to [ISO 15924 Standard](https://en.wikipedia.org/wiki/ISO_15924#List_of_codes) script code consists of 4 characters, which could be used to distinguish from country code which is 2 letters. So this could be implemented using the length of the code to decide which sub tag the code is for.

And while we're at it, why not support all 3 tags altogether too: e.g `zh_Hant_TW.arb`. Let me know if you'd like a PR on this.

**Comment by timfreiheit** [comment]
This sounds like a nice addition.
Pull Request are always welcome.

**Comment by chen-yumin** [comment]
Put out PR #20 aiming to address the lack of `scriptCode` support.

**Comment by chen-yumin** [comment]
Closing this issue. PR #20 addressed the feature request.
