### ISSUE TITLE
Avoid use of absolute paths in generated file

### ISSUE THREAD

**Issue by itsJoKr** [timfreiheit/r_flutter#21]
In the generated file I'll have something like:

`/// ![](file:///Users/itsJoKr/Documents/projects/Flutter-Project/assets/svg/invoice_icon.svg)`

When multiple people work on the same project these files will always have changes in them. Can I somehow remove this comment completely from generate because I would like to see clean git history?

**Comment by timfreiheit** [comment]
Generated files should not be committed to source control. Every member of your team should generate the file locally on their machine. This also applies for a ci server in case you are using one.

**Comment by itsJoKr** [comment]
Ok. Good point.

But I kinda liked the idea that you can clone the project and everything works out of the box.

Closing this.
