### ISSUE TITLE
Incompatible with build_runner 2.0

### ISSUE THREAD

**Issue by itsJoKr** [timfreiheit/r_flutter#32]
The new build_runner version (^2.0.0) depends on build_config > 1.0.0 and r_flutter ^0.7.1 requires build_config ^0.4.7.

This is very problematic because other packages can depend on build_runner 2.0.0, but I cannot update it because of r_flutter. Build_runner is a popular package that's also used in json serialization, freezed, mockito, etc.

To fix: update build_config dependency to >1.0.0.

**Comment by timfreiheit** [comment]
Thanks. 
version 0.8.0 contains the updated dependency
