### ISSUE TITLE
Asset generation - improvements

### ISSUE THREAD

**Issue by szotp** [timfreiheit/r_flutter#5]
I may do these soon:

1. Ignore dot files.

This should not be in my assets class
```
static const String dSStore = "resources/images/.DS_Store";
```

2. Document assets with images if possible.

Something like this: https://github.com/flutter/engine/blob/master/lib/ui/painting.dart#L417
I'm not sure if this can be done without absolute links. But if it worked, it would be super neat.

3. Somehow support .svg and maybe other types.

I'm using svg assets mostly, which means I have to deal with strings:
```
static const String cancel = "resources/images/icons/cancel.svg";
```
Maybe it would be possible to improve generation somehow to have something like this:
```
static const String cancel = AssetSvg("resources/images/icons/cancel.svg");
```
so it's easier to enforce that given function expects path to svg file, add helper method into it, etc. Could be totally hardcoded for svg, or maybe some kind of template / config is needed to support other file types.

**Comment by timfreiheit** [comment]
are you using [flutter_svg](//pub.dev/packages/flutter_svg)?
I was not sure if the plugin should create to much dependencies on other packages which might get a replacement in the future.
To make the constant fully usable there needs to be a way for the user to specify options like `scale` or the `colorFilter` as they can now in the `AssetPicture` class `AssetPicture('icons/heart.png', scale: 1.5)`

**Comment by szotp** [comment]
You are right, it's not a good idea to add more dependencies. That's why I was thinking about some kind of custom settings to specify the class. Maybe something like this:
```yaml
r_flutter:
  asset_classes:
    *.svg: AssetSvg
```

**Comment by timfreiheit** [comment]
one option could be to separate the `Assets` class into different classes based on the pattern.
```yaml
r_flutter:
  asset_classes:
    *.svg: AssetSvgs
```

could result in the class generated:
```dart
class SvgAssets {
  static const String icon = "lib/assets/icon.svg";
}
```

where you thinking about something like that?

**Comment by szotp** [comment]
No, I was thinking about a wrapper over string, to prevent the developer from passing incorrect asset. 

I'm fine with one Assets class because it gives single entry point for all assets.
